# 前后端分离部署配置
services:
  # 使用统一的 Dockerfile 构建完整应用
  openbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=sqlite:////app/data/openbook.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALLOWED_ORIGINS=["*"]
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - NEXT_PUBLIC_API_URL=/api
      - DEBUG=False
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
      - OAUTH_REDIRECT_URI=${FRONTEND_URL:-http://localhost}/api/auth/oauth/callback
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  data:
    driver: local
