# OpenBook 前后端分离部署配置
version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/openbook.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost", "*"]
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      
      # OAuth 2.0 配置
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
      - OAUTH_AUTHORIZATION_URL=${OAUTH_AUTHORIZATION_URL:-}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL:-}
      - OAUTH_USER_INFO_URL=${OAUTH_USER_INFO_URL:-}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI:-http://localhost/api/auth/oauth/callback}
      - OAUTH_SCOPE=${OAUTH_SCOPE:-openid email profile}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME:-OAuth Provider}
      - OAUTH_EMAIL_FIELD=${OAUTH_EMAIL_FIELD:-email}
      - OAUTH_NAME_FIELD=${OAUTH_NAME_FIELD:-name}
      - OAUTH_AVATAR_FIELD=${OAUTH_AVATAR_FIELD:-picture}
      - OAUTH_ID_FIELD=${OAUTH_ID_FIELD:-sub}
      - OAUTH_STATE_SECRET=${OAUTH_STATE_SECRET:-your-state-secret-change-in-production}
      - OAUTH_USE_PKCE=${OAUTH_USE_PKCE:-true}
      
      # 前端 URL (用于 OAuth 回调重定向)
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - openbook_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - openbook_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-separated.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - openbook_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:

networks:
  openbook_network:
    driver: bridge
